### ISSUE TITLE
How to migrate database ? 

### ISSUE THREAD

**Issue by brucellino** [FutureGateway/fgAPIServer#6]
I'm getting the error : 

```
Current database version '0.0.5' is not compatible with this version of the API server front-end; version 0.0.8 is required
```

How does one migrate from one version to another  ?

**Comment by ricsxn** [comment]
In fgAPIServer/db_patches directory, execute script: patch_apply.sh
Before to execute the script be sure to update the directory content with git
If you don't want to reach the latest version you can delete/rename patch versions not required.

**Comment by ricsxn** [comment]
Required DB version is currently located on fgapiserver.conf file. This value will be removed from config file (an issue will be soon available on this)
