### ISSUE TITLE
Why are  the db patches kept in scripts and not in change control ? 

### ISSUE THREAD

**Issue by brucellino** [FutureGateway/fgAPIServer#8]
When configuring the database, you do a loop through versions to get to the latest one. why not just keep the versions in sql under change control and apply the required one ?

**Comment by ricsxn** [comment]
Patches and DB migrations in general require 2 steps:

1) The change on DB schema
2) A procedure that manages the consistency after the DB schema change

The 2nd point must be in charge of a batch procedure, actually in the form of a script.
